### ISSUE TITLE
error with the ReadMe exemple

### ISSUE THREAD

**Issue by lalop** [vojtajina/node-di#14]
Testing the current exemple with car and engine, I get 

``` js
/Users/sam/Workspace/inspecteur-harry/node_modules/di/lib/injector.js:104
  modules.forEach(function(module) {
          ^
TypeError: Object #<Object> has no method 'forEach'
    at new Injector (/Users/sam/Workspace/inspecteur-harry/node_modules/di/lib/injector.js:104:11)
    at Object.<anonymous> (/Users/sam/Workspace/inspecteur-harry/cli.js:31:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:901:3
```

It seems that the README isn't up to date.

**Comment by xuwenmin** [comment]
i have the same error,so,i read source code,guess module should is array,see bottom code
var module = [
  // if an object asks for 'car', the injector will call new Car(...) to produce it
 { 'car': ['type', Car]},
  // if an object asks for 'engine', the injector will call createPetrolEngine(...) to produce it
  {'engine': ['factory', createPetrolEngine]},
  // if an object asks for 'power', the injector will give it number 1184
  {'power': ['value', 1184]} // probably Bugatti Veyron
];
above code is pass

**Comment by athlan** [comment]
Thank you @xuwenmin .
